# Global logging settings
default_level: WARNING
dev_level: INFO
verbose_level: DEBUG

# Error aggregation settings
error_aggregation:
  enabled: true
  report_interval: 3600  # Report every hour
  error_threshold: 5     # Report after 5 occurrences
  time_threshold: 300    # Or after 5 minutes
  categorize_by:
    - service
    - message
    - stack_trace

# File logging settings
file:
  enabled: true
  path: logs/golfcal.log
  max_size_mb: 50  # Larger file size for golf calendar data
  backup_count: 7  # Keep a week's worth of logs
  format: json
  include_timestamp: true

# Console logging settings
console:
  enabled: true
  format: text
  include_timestamp: true
  color: true

# Sampling configuration
sampling:
  debug_rate: 1.0    # Keep all debug logs
  info_rate: 1.0     # Keep all info logs
  warning_rate: 1.0  # Keep all warning logs
  error_rate: 1.0    # Keep all error logs
  critical_rate: 1.0 # Keep all critical logs

# Service-specific settings
services:
  # Weather service logging
  weather_service:
    level: DEBUG
    sampling:
      debug_rate: 1.0    # Only applies when verbose mode enabled
      info_rate: 1.0     # Keep all info logs
      warning_rate: 1.0  # Keep all warning logs
      error_rate: 1.0    # Keep all error logs
      critical_rate: 1.0 # Keep all critical logs
    sensitive_fields:
      - api_key
      - auth_token
      - aemet_key
      - openweather_key
    performance_logging: true
    file:
      enabled: true
      path: logs/weather.log
      max_size_mb: 20
      backup_count: 5

  # Calendar service logging
  calendar_service:
    level: DEBUG
    sampling:
      debug_rate: 0.2    # Only applies when verbose mode enabled
      info_rate: 1.0     # Keep all info logs
      warning_rate: 1.0  # Keep all warning logs
      error_rate: 1.0    # Keep all error logs
      critical_rate: 1.0 # Keep all critical logs
    performance_logging: true
    sensitive_fields:
      - ics_token
      - calendar_id
    file:
      enabled: true
      path: logs/calendar.log
      max_size_mb: 30
      backup_count: 7

  # Authentication service logging
  auth:
    level: WARNING
    sensitive_fields:
      - password
      - token
      - cookie
      - session_id
      - auth_details
      - wisegolf_token
      - nexgolf_token
    performance_logging: true
    file:
      enabled: true
      path: logs/auth.log
      max_size_mb: 10
      backup_count: 5

  # Reservation service logging
  reservation_service:
    level: DEBUG
    sampling:
      debug_rate: 0.2    # Only applies when verbose mode enabled
      info_rate: 1.0     # Keep all info logs
      warning_rate: 1.0  # Keep all warning logs
      error_rate: 1.0    # Keep all error logs
      critical_rate: 1.0 # Keep all critical logs
    sensitive_fields:
      - user_id
      - member_id
      - booking_token
    performance_logging: true
    file:
      enabled: true
      path: logs/reservation.log
      max_size_mb: 40
      backup_count: 7

  # Golf club service logging
  club_service:
    level: DEBUG
    sampling:
      debug_rate: 0.1    # Only applies when verbose mode enabled
      info_rate: 1.0     # Keep all info logs
      warning_rate: 1.0  # Keep all warning logs
      error_rate: 1.0    # Keep all error logs
      critical_rate: 1.0 # Keep all critical logs
    sensitive_fields:
      - club_id
      - member_number
      - access_token
    performance_logging: true
    file:
      enabled: true
      path: logs/club.log
      max_size_mb: 20
      backup_count: 5

# Library logging configuration
libraries:
  urllib3: WARNING
  requests: WARNING
  icalendar: WARNING
  yaml: WARNING
  json: WARNING

# Performance logging settings
performance:
  enabled: true
  slow_threshold_ms: 2000  # Log warning for operations slower than 2 seconds
  include_args: false      # Don't include function arguments in performance logs
  include_stack_trace: true

# Correlation ID settings
correlation:
  enabled: true
  include_in_console: true
  header_name: X-GolfCal-Correlation-ID

# Sensitive data masking
sensitive_data:
  enabled: true
  global_fields:
    - password
    - token
    - api_key
    - secret
    - credit_card
    - ssn
    - auth
    - cookie
    - session_id
    - access_token
    - refresh_token
    - wisegolf_token
    - nexgolf_token
    - aemet_key
    - openweather_key
  mask_pattern: "***MASKED***"
  partial_mask: false  # Don't show any part of sensitive data 