# Test events for weather providers across different time ranges

# Met.no service tests (Nordic/Baltic region)
# Short range (<48h)
- name: "Oslo GC Tomorrow"
  location: "Oslo Golf Club"
  coordinates:
    lat: 59.8940
    lon: 10.8282
  users:
    - "Jarkko"
  start_time: "tomorrow 10:00"
  end_time: "tomorrow 14:00"
  timezone: "Europe/Oslo"
  address: "Grønmo, 1279 Oslo, Norway"

# Medium range (48h-7d)
- name: "Oslo GC 4 Days"
  location: "Oslo Golf Club"
  coordinates:
    lat: 59.8940
    lon: 10.8282
  users:
    - "Jarkko"
  start_time: "4 days 09:00"
  end_time: "4 days 15:00"
  timezone: "Europe/Oslo"
  address: "Grønmo, 1279 Oslo, Norway"

# Long range (>7d)
- name: "Oslo GC Next Week"
  location: "Oslo Golf Club"
  coordinates:
    lat: 59.8940
    lon: 10.8282
  users:
    - "Jarkko"
  start_time: "9 days 09:00"
  end_time: "9 days 15:00"
  timezone: "Europe/Oslo"
  address: "Grønmo, 1279 Oslo, Norway"

# OpenMeteo service tests (default provider)
# Short range (<48h)
- name: "Lykia Links Tomorrow"
  location: "Lykia Links Golf Club"
  coordinates:
    lat: 36.7584
    lon: 31.5876
  users:
    - "Jarkko"
  start_time: "tomorrow 07:00"
  end_time: "tomorrow 17:00"
  timezone: "Europe/Istanbul"
  address: "Denizyaka Mah, Köprüçay Cd. No:12, 07600 Serik/Antalya, Turkey"

# Medium range (48h-7d)
- name: "PGA Catalunya 4 Days"
  location: "PGA Catalunya"
  coordinates:
    lat: 41.8789
    lon: 2.7649
  users:
    - "Jarkko"
  start_time: "4 days 09:30"
  end_time: "4 days 14:30"
  timezone: "Europe/Madrid"
  address: "Carretera N-II km 701, 17455 Caldes de Malavella, Girona, Spain"

# Long range (>7d)
- name: "PDR Next Week"
  location: "Praia D'El Rey Golf Club"
  coordinates:
    lat: 39.3722
    lon: -9.2858
  users:
    - "Jarkko"
  start_time: "9 days 08:00"
  end_time: "9 days 12:00"
  timezone: "Europe/Lisbon"
  address: "Vale de Janelas, 2514-999 Óbidos, Portugal"

# Edge case: timezone difference (Canary Islands)
- name: "Golf Costa Adeje"
  location: "Golf Costa Adeje"
  coordinates:
    lat: 28.0876
    lon: -16.7408
  users:
    - "Jarkko"
  start_time: "tomorrow 09:30"
  end_time: "tomorrow 14:30"
  timezone: "Atlantic/Canary"
  address: "Calle Alcojora, s/n, 38670 Adeje, Santa Cruz de Tenerife, Spain" 