# Ruff configuration file

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Same as Black.
line-length = 88

# Assume Python 3.10.
target-version = "py310"

[lint]
# Enable flake8-bugbear (`B`) rules.
select = ["E", "F", "B", "I"]

# Ignore specific rules
ignore = [
    "B904",  # Use 'raise ... from err' (within an except block)
    "E501",  # Line too long
    "E741",  # Ambiguous variable name
    "B019",  # Use of `functools.lru_cache` on methods can lead to memory leaks
    "B005",  # Using `.strip()` with multi-character strings is misleading
    "E722",  # Do not use bare `except`
    "F821",  # Undefined name
    "F811",  # Redefinition of unused name
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
# Tests can use assert
"tests/**/*.py" = ["S101"] 