events:
  # - name: "Cullinan Links (Olympos)"
  #   location: "Cullinan Links Golf Club"
  #   coordinates:
  #     lat: 36.860432
  #     lon: 30.969687
  #   users:
  #     - "Jarkko"
  #     - "Seven"
  #   start: "2024-12-31T10:00:00"
  #   end: "2024-12-31T14:15:00"
  #   timezone: "Europe/Istanbul"
  #   address: "Üçkumtepesi Mevkii, Belek, Antalya, Türkiye"

  # Example of a weekly recurring event
  - name: "Winter Practice 50514#"
    location: "Golfluola"
    coordinates:
      lat: 60.2859
      lon: 24.8427
    users:
      - "Jarkko"
      - "Seven"
    start: "2024-11-13T18:00:00"
    end: "2024-11-13T21:00:00"
    timezone: "Europe/Helsinki"
    address: "KEIMOLANMÄENTIE 11, HALLI 85, 01700 VANTAA"
    repeat:
      frequency: "weekly"    # can be 'weekly' or 'monthly'
      until: "2025-04-02"   # end date for the recurring events



 