name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
  
    - name: Install dependencies
      run: |
        uv pip install pytest pytest-cov ruff mypy types-requests types-PyYAML
        uv pip install -e ".[dev]"
    
    - name: Lint with ruff
      run: |
        # Use .ruff.toml configuration
        ruff check --fix --unsafe-fixes src tests
    
    - name: Type check with mypy
      run: |
        mypy src
    
    - name: Test with pytest
      run: |
        pytest --cov=src tests/